
// this file declares the constants used by the engine.
// the data.c definitions are generated by a pre-compile program  

#pragma once 

#include "core.h"

extern const U64 king_attacks[64];
extern const U64 wpawn_attacks[64];
extern const U64 bpawn_attacks[64];
extern const U64 knight_attacks[64];

extern const U8 rook_shifts[64];
extern const U8 bishop_shifts[64];

// unrestricted rook and bishop controls, including edge squares 
extern const U64 rook_attacks[64]; 
extern const U64 bishop_attacks[64]; 
// --//-- without edge squares 
extern const U64 rook_masks[64];
extern const U64 bishop_masks[64];
// magics and all blockers-attacks configurations for rooks and bishops  
extern const U64 rook_magics[64];
extern const U64 bishop_magics[64];
extern const U64 rook_configs[64][4096];
extern const U64 bishop_configs[64][512];

// values for zobrist hashing 
//extern const U64 zob_table[64][12]; // for each piece on each square 
//extern const U64 zob_castle[16]; // for each combination of castling rights 
//extern const U64 zob_en_passant[8]; // for each file on which an en passant might be legal 
//extern const U64 zob_turn; // if it is black's turn 

